theme: jekyll-theme-cayman
title: Rencontres des Utilisateurs Francophones de QGIS
description: [A short description of your site's purpose]
show_downloads: false
language: fr
is_user_page: false
is_project_page: false    
twitter:
  username: osgeo-fr
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"
