theme: jekyll-theme-cayman
show_downloads: false
title : Rencontres des Utilisateurs Francophones de QGIS
language: fr
is_user_page: false
is_project_page: false    
twitter:
  username: osgeo-fr
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"
